# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170914_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='points',
            field=models.CharField(max_length=50, verbose_name='\u6559\u5b66\u7279\u70b9'),
        ),
    ]
