# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20170916_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BigIntegerField(default=False, verbose_name='\u662f\u5426\u662f\u8f6e\u64ad\u56fe'),
        ),
    ]
